### PR TITLE
PHP 8.0 support 

### PR DESCRIPTION
**Pull request by pushpak1300**
Resolve https://github.com/kirschbaum-development/laravel-test-runner-container/issues/10 

PHP8.0-rc1 is currently working on ubuntu 20.04

also ondrej/php is not supporting php8.0-json and php8.0-imagick extension yet.
Once it starts supporting those extensions I will add those extensions.

https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php8.0&field.status_filter=published&field.series_filter=

Let me know if anything needs to be changed.
Thanks!

### CODE REVIEW

**Comment by pushpak1300** [comment]
@luisdalmolin You can review !

**Review by luisdalmolin — APPROVED** [review]
@pushpak1300 Nice, thanks for your contribution. I'll merge this and see if it builds correctly.

**Comment by pushpak1300** [comment]
@luisdalmolin Build is failing any reason?

**Comment by pushpak1300** [comment]
Also it will be great if you cam add hacktoberfest label to this pull request 😅

**Comment by luisdalmolin** [comment]
@pushpak1300 Build is failing, but I didn't have time to look yet. And sure, I'll add the label.

**Comment by pchhajed** [comment]
@luisdalmolin let me know what thing causing the failing because docker file is building on my local machine.

**Comment by pushpak1300** [comment]
@luisdalmolin let me know what thing caused the failing because docker file is building on my local machine.

**Comment by pushpak1300** [comment]
Sorry to bother you @luisdalmolin can you please add this label instead of hacktoberfest.

> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by luisdalmolin** [comment]
I've added the topic to the repo, hope is good now.

**Pull request merged**
